### PR TITLE
(#2026244) systemd memory corruption fixes

### PR DESCRIPTION
**Pull request by jamacku**

### CODE REVIEW

**Review by dtardon — DISMISSED** [review]
LGTM

**Comment by jamacku** [comment]
@mrc0mmand Could you please have a look at CI

**Comment by mrc0mmand** [comment]
> @mrc0mmand Could you please have a look at CI

Backporting https://github.com/redhat-plumbers/systemd-rhel8/commit/8c15742d1194e0db9a2555553e4d77ebb441b3dc should make it happy again. I wouldn't bother (for now) with backport of the ASan-related patches.

**Comment by mrc0mmand** [comment]
Whops, forgot about https://github.com/redhat-plumbers/systemd-rhel8/commit/b029865ef6d8b23ecdbfda4e277a3f75cb59ee94, sorry.

**Comment by jamacku** [comment]
@mrc0mmand I guess we are also missing some commits from #234

**Comment by mrc0mmand** [comment]
> @mrc0mmand I guess we are also missing some commits from #234

*sigh*, yeah, I forgot this is 8.4 branch. 

For CentOS CI https://github.com/redhat-plumbers/systemd-rhel8/commit/0357dced252b4bbd1b6dede64a8e0a6674eced6f should be enough.
For GH Actions, hopefully https://github.com/redhat-plumbers/systemd-rhel8/commit/68555d26da9e46efbd70703b39a81cee601d265a is all that's missing.

**Review by dtardon — APPROVED** [review]
LGTM

**Pull request merged**
