### PR TITLE
(#2123927) core: give a nicer error message on invalid aliases

### PR DESCRIPTION
**Pull request by jacekmigacz**
(cherry picked from commit c89d0c3b0567eb8fdf0b06a27f46c64245d2f0a4)

Resolves: #2123927

### CODE REVIEW

**Review by dtardon — APPROVED** [review]
LGTM

**Review by jamacku — CHANGES_REQUESTED** [review]
@jacekmigacz I think this PR should be opened on [redhat-plumbers/systemd-rhel9](https://github.com/redhat-plumbers/systemd-rhel9). Bug [#2123927](https://bugzilla.redhat.com/show_bug.cgi?id=2123927) is for CentOS Stream (RHEL9).

**Comment by jacekmigacz** [comment]
You are right @jamacku.

**Comment by msekletar** [comment]
Let's close this PR since it is for a bug in different RHEL version.

**Pull request closed without merging**
