### PR TITLE
(#1860899) Avoid a race when exiting user service

### PR DESCRIPTION
**Pull request by dtardon**

### CODE REVIEW

**Review by msekletar — APPROVED** [review]
LGTM

**Comment by jamacku** [comment]
@dtardon Could you please rebase. Thanks

**Comment by jamacku** [comment]
@mrc0mmand Could you please have a look at CI. Thanks

**Comment by mrc0mmand** [comment]
@lnykryn interesting, the GH API (as well as GH in general) had an outage and your bot just assumed that all CIs passed ;)

**Comment by jamacku** [comment]
@mrc0mmand That's known issue. We should check both [check-runs](https://docs.github.com/en/rest/reference/checks#list-check-runs-for-a-git-reference) and [check-suites](https://docs.github.com/en/rest/reference/checks#list-check-suites-for-a-git-reference), but we check only ``check-suites``. I'm looking to it.

**Comment by mrc0mmand** [comment]
> @mrc0mmand That's known issue. We should check both [check-runs](https://docs.github.com/en/rest/reference/checks#list-check-runs-for-a-git-reference) and [check-suites](https://docs.github.com/en/rest/reference/checks#list-check-suites-for-a-git-reference), but we check only `check-suites`. I'm looking to it.

I see, thank you. In the meantime, I fixed the CI issue in https://github.com/systemd/systemd-centos-ci/pull/441, so the CIs should be green once again.

**Comment by jamacku** [comment]
@mrc0mmand @systemd-rhel-bot  shouldn't be able to merge PR with failing CI for now. I protected all branches and CI is now required together with one review.

**Comment by mrc0mmand** [comment]
> @mrc0mmand @systemd-rhel-bot shouldn't be able to merge PR with failing CI for now. I protected all branches and CI is now required together with one review.

Excellent, thanks!

**Pull request merged**
