### PR TITLE
(#1860899) avoid a race when exiting user service

### PR DESCRIPTION
**Pull request by dtardon**

### CODE REVIEW

**Review by msekletar — APPROVED** [review]
LGTM

**Comment by msekletar** [comment]
@mrc0mmand CentOS CI failed (most likely) because it ran only of subset of the test-suite. However, those tests that ran PASSed. Do you have an idea what might be going on?

**Comment by mrc0mmand** [comment]
So, after trying to reproduce this locally, I think the issue is apparent:

```
# systemctl reboot
Failed to reboot system via logind: Unit systemd-reboot.service has a bad unit file setting.
Failed to start reboot.target: Unit systemd-reboot.service has a bad unit file setting.
See system logs and 'systemctl status reboot.target' for details.
# journalctl -e --no-hostname -o short-monotonic
...
[  644.920482] systemd[1]: systemd-reboot.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
[  644.922012] systemd-logind[1107]: System is rebooting.
[  644.924050] systemd[1]: systemd-reboot.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
[  644.930398] systemd[1]: systemd-reboot.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
[  660.864236] systemd[1]: systemd-reboot.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
[  660.865838] systemd[1]: systemd-reboot.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
[  940.011528] systemd[1]: Starting Cleanup of Temporary Directories...
[  940.072939] systemd[1]: Started Cleanup of Temporary Directories.
```

**Review by msekletar — CHANGES_REQUESTED** [review]
@dtardon it seems that we need to further adjust our code so that service units are not required to have [Service] section with ExecStart or ExecStop specified.

**Comment by dtardon** [comment]
> @dtardon it seems that we need to further adjust our code so that service units are not required to have [Service] section with ExecStart or ExecStop specified.

That's already done by https://github.com/systemd-rhel/rhel-8/pull/136/commits/84f1cc07a43be068c54c0e257a8b5652a55835f4.

**Comment by dtardon** [comment]
> So, after trying to reproduce this locally, I think the issue is apparent:
> 
> ```
> # systemctl reboot
> Failed to reboot system via logind: Unit systemd-reboot.service has a bad unit file setting.
> Failed to start reboot.target: Unit systemd-reboot.service has a bad unit file setting.
> See system logs and 'systemctl status reboot.target' for details.
> # journalctl -e --no-hostname -o short-monotonic
> ...
> [  644.920482] systemd[1]: systemd-reboot.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
> ```

@mrc0mmand You run daemon-reload, but not daemon-reexec, right? Because this error message doesn't exist in the new code.

**Comment by mrc0mmand** [comment]
> > So, after trying to reproduce this locally, I think the issue is apparent:
> > ```
> > # systemctl reboot
> > Failed to reboot system via logind: Unit systemd-reboot.service has a bad unit file setting.
> > Failed to start reboot.target: Unit systemd-reboot.service has a bad unit file setting.
> > See system logs and 'systemctl status reboot.target' for details.
> > # journalctl -e --no-hostname -o short-monotonic
> > ...
> > [  644.920482] systemd[1]: systemd-reboot.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
> > ```
> 
> @mrc0mmand You run daemon-reload, but not daemon-reexec, right? Because this error message doesn't exist in the new code.

Hah, this is a pretty good point, because right now there's neither `daemon-reload` nor `daemon-reexec` issued after `meson install. I'll look into that.

**Review by mrc0mmand — CHANGES_REQUESTED** [review]
So, after I added `daemon-reexecute` to the bootstrap script, there's still something amiss when trying to reboot the machine:

```
[  661.411571] systemd[1]: Reexecuting.
[  661.405052] kernel: printk: systemd: 61 output lines suppressed due to ratelimiting
[  661.433798] systemd[1]: systemd 239 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=le>
[  661.466907] systemd[1]: Detected architecture x86-64.
...
[  695.453387] sshd[8320]: Received disconnect from 172.19.0.16 port 51392:11: disconnected by user
[  695.455169] sshd[8320]: Disconnected from user root 172.19.0.16 port 51392
[  695.458583] sshd[7220]: pam_unix(sshd:session): session closed for user root
[  695.462650] systemd-logind[1269]: Session 5 logged out. Waiting for processes to exit.
[  695.463129] systemd[1]: session-5.scope: Succeeded.
[  695.465834] systemd-logind[1269]: Removed session 5.
[  695.468416] systemd[1]: Stopping User Manager for UID 0...
[  695.469464] systemd[8204]: /usr/lib/systemd/user/systemd-exit.service:16: Failed to parse failure action specifier, ignoring: exit-force
[  695.470204] systemd[8204]: systemd-exit.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
[  695.470298] systemd[8204]: Failed to enqueue exit.target job: Unit systemd-exit.service has a bad unit file setting.
[  695.912672] sshd[76764]: Accepted publickey for root from 172.19.0.16 port 52030 ssh2: RSA SHA256:XI6P95wU3TyZqN8YTWLscn48i9t+dMg1xgN9BgfCmDo
[  695.925909] systemd-logind[1269]: New session 7 of user root.
[  695.926594] systemd[1]: Started Session 7 of user root.
[  695.926939] sshd[76764]: pam_systemd(sshd:session): Failed to create session: Start job for unit user-0.slice failed with 'canceled'
[  695.927219] sshd[76764]: pam_unix(sshd:session): session opened for user root by (uid=0)
[  696.106530] sshd[76767]: Received disconnect from 172.19.0.16 port 52030:11: disconnected by user
[  696.107352] sshd[76767]: Disconnected from user root 172.19.0.16 port 52030
[  696.108403] sshd[76764]: pam_unix(sshd:session): session closed for user root
[  696.118028] systemd[1]: session-7.scope: Succeeded.
[  696.120338] systemd-logind[1269]: Session 7 logged out. Waiting for processes to exit.
[  696.121566] systemd-logind[1269]: Removed session 7.
[  696.661387] sshd[76778]: Accepted publickey for root from 172.19.0.16 port 52032 ssh2: RSA SHA256:XI6P95wU3TyZqN8YTWLscn48i9t+dMg1xgN9BgfCmDo
[  696.670154] systemd-logind[1269]: New session 8 of user root.
[  696.670952] systemd[1]: Started Session 8 of user root.
[  721.691486] sshd[76778]: pam_systemd(sshd:session): Failed to create session: Connection timed out
...
```

**Comment by mrc0mmand** [comment]
Nevermind the previous comment, I think I know where the issue is...

**Comment by mrc0mmand** [comment]
So, yeah, as I suspected - I had to do both `systemctl daemon-reexec` and `systemctl --user daemon-reexec` to be able to reboot the machine, otherwise issuing `systemctl reboot` would end up with the aforementioned error.

I see that we do `systemctl daemon-reexec` in the systemd spec file, but wouldn't the user instance cause potential issues after upgrading to this revision?

**Comment by msekletar** [comment]
I think we should be reexecuting all systemd instances after `ninja install` and on rpm updates. However, that is a specfile change so it shouldn't block merging this PR.

**Comment by gleventhal** [comment]
I haven't dug into this change specifically yet, but we seem to be leaking sessions after getting 239-58.el8 which introduced this fix..  It seems like the --user managers are keeping very old sessions, which remain in "State: opening" and "State: closing". 

I dont find relevant FIFOs $n.ref under /run/systemd/sessions for these stale session files, and they cause us to hit the session-max defined in logind.conf, even when its 16384.  

This causes Dbus to slow to a crawl, etc... Restarting systemd-logind often resolves the leak, sometimes I need to rm the stale ression files under /run/systemd/sessions first, using this monstrosity:

```
find /run/systemd/sessions/ -type f -name '[0-9]*' -a ! -name '*.ref' | xargs -I{} bash -c 'grep SCOPE {} | cut -f2 -d= |xargs systemctl status >/dev/null 2>&1 || rm -f {}'
```

**Pull request merged**
