### PR TITLE
Use less in "secure" mode when run under sudo

### PR DESCRIPTION
**Pull request by dtardon**
Resolves: [#2175623](https://bugzilla.redhat.com/show_bug.cgi?id=2175623)

### CODE REVIEW

**Comment by msekletar** [comment]
CI failure is unrelated and already addressed in #374

**Review by msekletar — DISMISSED** [review]
LGTM

**Comment by msekletar** [comment]
Hi @dtardon, we need one followup because of how the build system is set up for RHEL-8. I've created PR #376 with the follow-up for `rhel-8.7.0` branch, please add that commit also here.

**Review by jamacku — APPROVED** [review]
LGTM

**Pull request merged**
