### PR TITLE
(#2030027) Do not fail if the same alt. name is set again

### PR DESCRIPTION
**Pull request by dtardon**
This is a workaround for a kernel bug.

RHEL-only

Resolves: #2030027

### CODE REVIEW

**Comment by mrc0mmand** [comment]
@dtardon please backport https://github.com/redhat-plumbers/systemd-rhel8/commit/4433c31a80c4477b0a0c503c74e8faebc44f4453 as well, to make CentOS CI happy

**Comment by dtardon** [comment]
> @dtardon please backport [4433c31](https://github.com/redhat-plumbers/systemd-rhel8/commit/4433c31a80c4477b0a0c503c74e8faebc44f4453) as well, to make CentOS CI happy

Done.

**Comment by msekletar** [comment]
@dtardon hmm CI is still unhappy. Seems like we also need 7c5fd25119a495009ea62f79e5daec34cc464628.

**Comment by msekletar** [comment]
Small, nit, can you not use -x for cherry-pick when you are cherry-picking from the different downstream branch? Two (cherry-picked ...) lines are confusing. Just keep the reference to upstream commit as with all other commits. Thanks!

**Comment by dtardon** [comment]
Done.

**Review by msekletar — APPROVED** [review]
LGTM

**Pull request merged**
