### PR TITLE
(#1788085) fix false journald assert

### PR DESCRIPTION
**Pull request by jsynacek**

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Ignore the CentOS CI fail for now, it's already under investigation, will re-trigger it after the issue is resolved.

**Review by dtardon — APPROVED** [review]
LGTM

**Comment by jsynacek** [comment]
The CentOS CI failure looks like some kind of internal error and totally unrelated to the patch.

**Comment by mrc0mmand** [comment]
> The CentOS CI failure looks like some kind of internal error and totally unrelated to the patch.

Whoops, sorry, my bad. I actually fixed the CI issue but forgot to reschedule the job. Done it now and it seems to be running well, results should be up in ~10 minutes.

**Pull request merged**
