### PR TITLE
(#1946671) Avoid needless PropertiesChanged signal

### PR DESCRIPTION
**Pull request by msekletar**

### CODE REVIEW

**Comment by msekletar** [comment]
Travis CI fails due to docker hub pull rate-limiting.

I think we should disable Travis CI on all branches. @mrc0mmand what do you think?

**Comment by mrc0mmand** [comment]
> Travis CI fails due to docker hub pull rate-limiting.
> 
> I think we should disable Travis CI on all branches. @mrc0mmand what do you think?

Definitely makes sense. I disabled the Travis integration for this repository.

**Review by dtardon — APPROVED** [review]
LGTM

**Comment by mrc0mmand** [comment]
The CentOS CI fail is expected (8.2 branch is missing https://github.com/systemd-rhel/rhel-8/pull/107).

**Pull request merged**
