### PR TITLE
(#2053273) Let SysV compat. shutdown commands honor inhibitors for root

### PR DESCRIPTION
**Pull request by dtardon**
Resolves: [#2053273](https://bugzilla.redhat.com/show_bug.cgi?id=2053273)

### CODE REVIEW

**Comment by dtardon** [comment]
@msekletar It just occurred to me that there's an easier--and safer--way than trying to make the _new_ code backwards-compatible again. Given that the changes are in a single function `halt_main`, we could add the whole function under a new name and then call the either old one or the new one as needed. Something like:
```
static int halt_main(void) {
        if (env_var_is_set())
                return halt_main_new();
        else
                return halt_main_old();
}
```

**Comment by msekletar** [comment]
That sounds much better. Please try to implement it this way so we know how exactly would resulting code look.

**Comment by dtardon** [comment]
Done.

**Review by msekletar — APPROVED** [review]
LGTM

**Pull request merged**
