### PR TITLE
(#1761519) TEST-02-CRYPTSETUP fixes

### PR DESCRIPTION
**Pull request by mrc0mmand**
This (partially) fixes TEST-02-CRYPTSETUP when run on RHEL8.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
The "partially" word from the comment above can be dropped, as I finally found the reason why systemd-journald kept SIGABRT-ing during TEST-02-CRYPTSETUP on RHEL8.

Basically, LUKS2 requires a slightly more space when storing relevant metadata, thus the 10M partition, used in the test, provides basically no other space for the journal itself:
```
[root@xxx rhel-8]# dd if=/dev/zero of=testdev bs=1M count=10
10+0 records in
10+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 0.00336339 s, 3.1 GB/s
[root@xxx rhel-8]# losetup --show -f testdev
/dev/loop0
[root@xxx rhel-8]# echo -n test > keyfile
[root@xxx rhel-8]# cryptsetup -q luksFormat --pbkdf pbkdf2 --pbkdf-force-iterations 1000 /dev/loop0 keyfile
[root@xxx rhel-8]# cryptsetup luksOpen /dev/loop0 testdev < keyfile
[root@xxx rhel-8]# mkfs.ext4 /dev/mapper/testdev 
mke2fs 1.44.3 (10-July-2018)
Creating filesystem with 2048 1k blocks and 256 inodes

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (1024 blocks): done
Writing superblocks and filesystem accounting information: done

[root@xxx rhel-8]# lsblk /dev/mapper/testdev 
NAME    MAJ:MIN RM SIZE RO TYPE  MOUNTPOINT
testdev 253:3    0   2M  0 crypt 
```

As you can see above, from the original 10M partition we have only 2M left for the actual data, which is less than what journald requires for a single journal file (5M).

Just for comparison, the same test with LUKS1:
```
# cryptsetup -q luksFormat --type luks1 /dev/loop0 keyfile
# cryptsetup luksOpen /dev/loop0 testdev < keyfile
# mkfs.ext4 /dev/mapper/testdev
# lsblk /dev/mapper/testdev 
NAME    MAJ:MIN RM SIZE RO TYPE  MOUNTPOINT
testdev 253:3    0   8M  0 crypt 
```

With LUKS1 there's enough space for a journal file - that's why the test works on RHEL7.

**Comment by mrc0mmand** [comment]
Thanks to @msekletar's hint I was able to obtain a coredump, which should shed more light into the SIGABRT issue:

```
Core was generated by `/usr/lib/systemd/systemd-journald'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	  return ret;
[Current thread is 1 (Thread 0x7fa19e4ede00 (LWP 506))]
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {17179888130, 1, 0, 0, 0, 0, 0, 0, 0, 0, 250000, 140731109650888, 4294967295, 100, 25030656, 140332110491520}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fa19d5f1c95 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7fa19e00e930 <__PRETTY_FUNCTION__.14184>, sa_sigaction = 0x7fa19e00e930 <__PRETTY_FUNCTION__.14184>}, sa_mask = {__val = {7932804595712, 140332117314315, 180388626432, 224, 0, 
              140731109649520, 140332116060183, 0, 0, 0, 0, 0, 140332117186800, 140332117322032, 140332117314315, 140332117314306}}, sa_flags = 1847, sa_restorer = 0x7ffe83ccaca0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fa19deda870 in log_assert_failed_realm (realm=LOG_REALM_SYSTEMD, text=0x7fa19e00cb02 "f", file=0x7fa19e00cb0b "../src/journal/journal-file.c", line=1847, 
    func=0x7fa19e00e930 <__PRETTY_FUNCTION__.14184> "journal_file_post_change") at ../src/basic/log.c:806
No locals.
#3  0x00007fa19dfad0a1 in journal_file_post_change (f=0x0) at ../src/journal/journal-file.c:1847
        __PRETTY_FUNCTION__ = "journal_file_post_change"
        __func__ = "journal_file_post_change"
#4  0x0000556f0b5bd3df in server_flush_to_var (s=0x7ffe83ccafd0, require_flag_file=false) at ../src/journal/journald-server.c:1044
        machine = {bytes = "\305\063\255j\252\003K\000\210r[X\365]\214", <incomplete sequence \321>, qwords = {21114653722358725, 15099546958997189256}}
        j = 0x556f0cc14b20
        ts = "\240\255̃\376\177\000\000\221\243읡\177\000\000p\317\300\foU\000\000\200\276\300\foU\000\000\220\256̃\376\177", '\000' <repeats 11 times>, "\256̃\376\177\000\000n\260읡\177\000"
        start = 6998998
        n = 746
        r = -5
        __PRETTY_FUNCTION__ = "server_flush_to_var"
        __func__ = "server_flush_to_var"
#5  0x0000556f0b5be02d in dispatch_sigusr1 (es=0x556f0cc0eb70, si=0x556f0cc0ebe0, userdata=0x7ffe83ccafd0) at ../src/journal/journald-server.c:1189
        s = 0x7ffe83ccafd0
        r = -2083738000
        __PRETTY_FUNCTION__ = "dispatch_sigusr1"
        __func__ = "dispatch_sigusr1"
#6  0x00007fa19df9827a in source_dispatch (s=0x556f0cc0eb70) at ../src/libsystemd/sd-event/sd-event.c:3115
        saved_type = SOURCE_SIGNAL
        r = 0
        __PRETTY_FUNCTION__ = "source_dispatch"
        __func__ = "source_dispatch"
#7  0x00007fa19df99ad5 in sd_event_dispatch (e=0x556f0cc0e190) at ../src/libsystemd/sd-event/sd-event.c:3516
        ref = 0x556f0cc0e190
        p = 0x556f0cc0eb70
        r = 1
        __PRETTY_FUNCTION__ = "sd_event_dispatch"
#8  0x00007fa19df99fbb in sd_event_run (e=0x556f0cc0e190, timeout=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:3573
        r = 1
        __PRETTY_FUNCTION__ = "sd_event_run"
#9  0x0000556f0b5b3b2e in main (argc=1, argv=0x7ffe83ccb3c8) at ../src/journal/journald.c:92
        t = 18446744073709551615
        n = 1571748885849031
        server = {syslog_fd = 3, native_fd = 5, stdout_fd = 4, dev_kmsg_fd = 7, audit_fd = -1, hostname_fd = 8, notify_fd = 12, event = 0x556f0cc0e190, syslog_event_source = 0x556f0cc0e560, native_event_source = 0x556f0cc0e660, 
          stdout_event_source = 0x556f0cc0e460, dev_kmsg_event_source = 0x556f0cc0e760, audit_event_source = 0x0, sync_event_source = 0x556f0cc10430, sigusr1_event_source = 0x556f0cc0eb70, sigusr2_event_source = 0x556f0cc0ed10, 
          sigterm_event_source = 0x556f0cc0ee10, sigint_event_source = 0x556f0cc0efd0, sigrtmin1_event_source = 0x556f0cc0f0f0, hostname_event_source = 0x556f0cc0e860, notify_event_source = 0x556f0cc0f7c0, 
          watchdog_event_source = 0x556f0cc0f900, runtime_journal = 0x556f0cc15dc0, system_journal = 0x0, user_journals = 0x556f0cc0d118, seqnum = 1217, buffer = 0x0, buffer_size = 0, rate_limit = 0x556f0cc0f2d0, 
          sync_interval_usec = 300000000, rate_limit_interval = 30000000, rate_limit_burst = 10000, runtime_storage = {name = 0x556f0b5d46e5 "Runtime journal", path = 0x556f0cc0f740 "/run/log/journal/c533ad6aaa034b0088725b58f55d8cd1", 
            metrics = {max_size = 3129344, min_size = 524288, max_use = 25030656, min_use = 3129344, keep_free = 37548032, n_max_files = 100}, space = {timestamp = 0, available = 0, limit = 0, vfs_used = 0, vfs_available = 0}}, 
          system_storage = {name = 0x556f0b5d46f5 "System journal", path = 0x556f0cc0f780 "/var/log/journal/c533ad6aaa034b0088725b58f55d8cd1", metrics = {max_size = 524288, min_size = 524288, max_use = 1048576, min_use = 1048576, 
              keep_free = 155648, n_max_files = 100}, space = {timestamp = 6998953, available = 523264, limit = 1048576, vfs_used = 525312, vfs_available = 394240}}, compress = {enabled = true, threshold_bytes = 18446744073709551615}, 
          seal = true, read_kmsg = true, forward_to_kmsg = false, forward_to_syslog = false, forward_to_console = false, forward_to_wall = true, n_forward_syslog_missed = 0, last_warn_forward_syslog_missed = 0, 
          var_available_timestamp = 0, max_retention_usec = 0, max_file_usec = 2629800000000, oldest_file_usec = 1571748884942798, stdout_streams = 0x556f0cc13050, stdout_streams_notify_queue = 0x0, n_stdout_streams = 3, tty_path = 0x0, 
          max_level_store = 7, max_level_syslog = 7, max_level_kmsg = 5, max_level_console = 6, max_level_wall = 0, storage = STORAGE_AUTO, split_mode = SPLIT_UID, mmap = 0x556f0cc0e110, deferred_closes = 0x556f0cc0be48, 
          udev = 0x556f0cc0f2b0, kernel_seqnum = 0x7fa19e4fd000, dev_kmsg_readable = true, send_watchdog = false, sent_notify_ready = true, sync_scheduled = true, machine_id_field = "_MACHINE_ID=c533ad6aaa034b0088725b58f55d8cd1", 
          boot_id_field = "_BOOT_ID=987987b99e50443b92b72125fbcaaa91", hostname_field = 0x556f0cc0bd80 "_HOSTNAME=systemd-testsuite", cgroup_root = 0x556f0cc0f700 "", watchdog_usec = 180000000, last_realtime_clock = 1571748885848881, 
          line_max = 49152, client_contexts = 0x556f0cc0beb8, client_contexts_lru = 0x556f0cc0fa00, last_cache_pid_flush = 6046583, my_context = 0x556f0cc0fa20, pid1_context = 0x556f0cc0fc00}
        r = 0
--Type <RET> for more, q to quit, c to continue without paging--
        __func__ = "main"
```

This can be reproduced by running `TEST-02-CRYPTSETUP` on RHEL8 with following settings:

```diff
diff --git a/test/TEST-02-CRYPTSETUP/test.sh b/test/TEST-02-CRYPTSETUP/test.sh
index 97eb2f409..55fcd33ed 100755
--- a/test/TEST-02-CRYPTSETUP/test.sh
+++ b/test/TEST-02-CRYPTSETUP/test.sh
@@ -63,6 +63,13 @@ After=multi-user.target
 ExecStart=/bin/sh -x -c 'systemctl --state=failed --no-legend --no-pager > /failed ; echo OK > /testok'
 Type=oneshot
 EOF
+       JOURNAL_DROPDIR="$initdir/etc/systemd/system/systemd-journald.service.d"
+       mkdir -p $JOURNAL_DROPDIR
+       cat > $JOURNAL_DROPDIR/99-coredump.conf << EOF
+[Service]
+ExecStartPre=/bin/bash -c 'ulimit -c unlimited; echo /root/core >  /proc/sys/kernel/core_pattern'
+EOF
+       rm $initdir//usr/lib/sysctl.d/50-coredump.conf
 
         setup_testsuite
 
diff --git a/test/test-functions b/test/test-functions
index fe25a501d..af9d16140 100644
--- a/test/test-functions
+++ b/test/test-functions
@@ -433,7 +433,7 @@ create_empty_image() {
     [ -b "$LOOPDEV" ] || return 1
     echo "LOOPDEV=$LOOPDEV" >> $STATEFILE
     sfdisk "$LOOPDEV" <<EOF
-,350M
+,390M
 ,
 EOF
```

```
# meson build -Dc_args='-g -O0 -fno-omit-frame-pointer -ftrapv'
# ninja -C build
# dracut -f --regenerate-all --filesystems ext4
# export QEMU_TIMEOUT=120
# export STRIP_BINARIES=no
# export KERNEL_APPEND="systemd.log_level=debug systemd.log_target=console kernel.suid_dumpable=1"
# make -C test/TEST-02-CRYPTSETUP/ clean setup run
```

**Comment by mrc0mmand** [comment]
After digging a little bit deeper, the fix for this issue seems to be https://github.com/systemd/systemd/commit/fd790d6f09b10a87b007b71403cb018f18ff91c9

**Comment by mrc0mmand** [comment]
Dropping the last patch, as it's already being backported by @dtardon in https://github.com/systemd-rhel/rhel-8/pull/32

**Review by dtardon — APPROVED** [review]
LGTM

**Pull request merged**
