### PR TITLE
(RHEL-5863) service: schedule cleanup of PID hashmaps when we now longer have mai…

### PR DESCRIPTION
**Pull request by msekletar**
…n_pid and we are in container

RHEL-only

Resolves: RHEL-5863

### CODE REVIEW

**Comment by mrc0mmand** [comment]
(The C8S fail is unrelated, working on a workaround, will restart the job once it's ready.)

**Comment by msekletar** [comment]
It is not clear at this point whether we end up using this proposed fix or not but I'd appreciate early look from @dtardon. Please let me know what do you think.

**Comment by msekletar** [comment]
Customer confirmed that issue is indeed fix by this cgroup v1 workaround. @dtardon I'd appreciate if you could take a look and give it yay or nay.

**Review by dtardon — APPROVED** [review]
LGTM

**Pull request merged**
