### PR TITLE
(#2095950) /p/s/mountinfo ratelimit followups

### PR DESCRIPTION
**Pull request by msekletar**

### CODE REVIEW

**Review by dtardon — COMMENTED** [review]
Don't we also need https://github.com/redhat-plumbers/systemd-rhel8/pull/290?

**Comment by msekletar** [comment]
We do but that is filed under different bugzilla so I will send separate PR for that.

**Comment by dtardon** [comment]
> We do but that is filed under different bugzilla so I will send separate PR for that.

All right.

**Review by dtardon — APPROVED** [review]
LGTM

**Comment by msekletar** [comment]
@dtardon  But before I submit that PR I think we will also need RHEL-8.4 variant of #280. Can you submit it once this is merged?

**Comment by dtardon** [comment]
> @dtardon But before I submit that PR I think we will also need RHEL-8.4 variant of #280. Can you submit it once this is merged?

The code depends on this one. There is no point submitting it before this one is merged (and resolving merge conflicts two times).

**Comment by msekletar** [comment]
> The code depends on this one. There is no point submitting it before this one is merged

Sure, that is why I wrote "...once this is merged" ;-)

**Comment by dtardon** [comment]
Well, I didn't read past the first sentence :-)

https://github.com/redhat-plumbers/systemd-rhel8/pull/293

**Pull request merged**
