### PR TITLE
(#1984406) sd-event ratelimiting followups

### PR DESCRIPTION
**Pull request by jamacku**
Relaces #199

### CODE REVIEW

**Review by dtardon — COMMENTED** [review]
#191 is a follow-up fix for the `copy_file_range` rework, so it should be included too.

**Review by dtardon — APPROVED** [review]
LGTM

**Review by mrc0mmand — APPROVED** [review]
Also LGTM, thanks!

**Comment by jamacku** [comment]
@lnykryn Could you please check bot? Thanks.

**Pull request merged**
