### PR TITLE
(#1871827) ci: move jobs from Travis CI to GH Actions

### PR DESCRIPTION
**Pull request by mrc0mmand**

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Hmpf, `test-engine` is not happy, not sure why it didn't show on Travis:

```
111/316 test-engine                             FAIL     0.32 s (exit status 1)

--- command ---
PATH='/build/build:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' SYSTEMD_KBD_MODEL_MAP='/build/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/build/src/locale/language-fallback-map' /build/build/test-engine
--- Listing only the last 100 lines from a long log. ---
		Requires: -.slice (origin-file)
		WantedBy: b.service (destination-file)
		Conflicts: shutdown.target (origin-default)
		Before: shutdown.target (origin-default)
		After: -.slice (origin-file)
		After: -.mount (origin-file)
		After: basic.target (origin-default)
		References: -.slice (origin-file)
		References: basic.target (origin-default)
		References: shutdown.target (origin-default)
		References: -.mount (origin-file)
		ReferencedBy: b.service (destination-file)
		RequiresMountsFor: /root (origin-file)
		StopWhenUnneeded: no
		RefuseManualStart: no
		RefuseManualStop: no
		DefaultDependencies: yes
		OnFailureJobMode: replace
		IgnoreOnIsolate: no
		Service State: dead
		Result: success
		Reload Result: success
		PermissionsStartOnly: no
		RootDirectoryStartOnly: no
		RemainAfterExit: no
		GuessMainPID: yes
		Type: simple
		Restart: no
		NotifyAccess: none
		NotifyState: unknown
		RestartSec: 100ms
		TimeoutStartSec: 1min 30s
		TimeoutStopSec: 1min 30s
		RuntimeMaxSec: infinity
		WatchdogSec: 0
		KillMode: control-group
		KillSignal: SIGTERM
		SendSIGKILL: yes
		SendSIGHUP:  no
		UMask: 
--- stderr ---
Found container virtualization none.
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
Using cgroup controller name=systemd. File system hierarchy is at /sys/fs/cgroup/systemd/actions_job/2ca6fb1b3c4fda1ea2ca36deddf49b0aa046ed3fb02e52e427debd4effe3fcca/actions_job/2ca6fb1b3c4fda1ea2ca36deddf49b0aa046ed3fb02e52e427debd4effe3fcca/75db2df8b878b402.
Controller 'cpu' supported: yes
Controller 'cpuacct' supported: yes
Controller 'cpuset' supported: no
Controller 'io' supported: no
Controller 'blkio' supported: yes
Controller 'memory' supported: yes
Controller 'devices' supported: yes
Controller 'pids' supported: yes
Looking for unit files in (higher priority first):
	/build/test
mnt.mount: Failed to load configuration: No such file or directory
mnt-swapfile.mount: Failed to load configuration: No such file or directory
root.mount: Failed to load configuration: No such file or directory
sys.mount: Failed to load configuration: No such file or directory
sys-kernel.mount: Failed to load configuration: No such file or directory
etc.mount: Failed to load configuration: No such file or directory
dev.mount: Failed to load configuration: No such file or directory
Successfully created private D-Bus server.
Bus bus-system: changing state UNSET → OPENING
Bus bus-system: changing state OPENING → AUTHENTICATING
Successfully connected to system bus.
Invoking unit coldplug() handlers…
mnt-swapfile.swap: Changed dead -> active
init.scope changed dead -> running
-.slice changed dead -> active
sys-kernel-config.mount: Changed dead -> mounted
etc-resolv.conf.mount: Changed dead -> mounted
build.mount: Changed dead -> mounted
etc-hosts.mount: Changed dead -> mounted
-.mount: Changed dead -> mounted
etc-hostname.mount: Changed dead -> mounted
sys-kernel-debug.mount: Changed dead -> mounted
dev-mqueue.mount: Changed dead -> mounted
Invoking unit catchup() handlers…
var.mount: Failed to load configuration: No such file or directory
var-tmp.mount: Failed to load configuration: No such file or directory
tmp.mount: Failed to load configuration: No such file or directory
slices.target: Failed to load configuration: No such file or directory
paths.target: Failed to load configuration: No such file or directory
swap.target: Failed to load configuration: No such file or directory
local-fs.target: Failed to load configuration: No such file or directory
emergency.target: Failed to load configuration: No such file or directory
emergency.service: Failed to load configuration: No such file or directory
../src/core/swap.c:1261:16: runtime error: member access within null pointer of type 'struct Swap'
    #0 0x562c5f03f1ee in swap_following ../src/core/swap.c:1261
    #1 0x562c5edf6fd1 in unit_following ../src/core/unit.c:3855
    #2 0x562c5edca7bf in unit_dump ../src/core/unit.c:1216
    #3 0x562c5ed7d209 in manager_dump_units ../src/core/manager.c:2029
    #4 0x562c5ed5d89d in main ../src/test/test-engine.c:46
    #5 0x7f29035757b2 in __libc_start_main (/lib64/libc.so.6+0x237b2)
    #6 0x562c5ed5c95d in _start (/build/build/test-engine+0x49195d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/core/swap.c:1261:16 in 
```

/cc @msekletar @dtardon

**Comment by dtardon** [comment]
We need https://github.com/systemd/systemd/commit/bbf11206230d1b089118971f98a047151cb5c4fa.

**Comment by mrc0mmand** [comment]
> We need [systemd/systemd@bbf1120](https://github.com/systemd/systemd/commit/bbf11206230d1b089118971f98a047151cb5c4fa).

Thanks a lot, now the test suite passes under sanitizers once again.

**Review by dtardon — APPROVED** [review]
LGTM

**Pull request merged**
