### PR TITLE
(RHEL-18302) coredump: actually store parsed unit in the context

### PR DESCRIPTION
**Pull request by msekletar**
RHEL-only

Related: RHEL-18302

### CODE REVIEW

**Comment by dtardon** [comment]
Oops...

**Review by dtardon — APPROVED** [review]
LGTM

**Comment by msekletar** [comment]
Unit test failures look unrelated, @mrc0mmand can you please double check and confirm?

**Comment by mrc0mmand** [comment]
> Unit test failures look unrelated, @mrc0mmand can you please double check and confirm?

It seems unrelated, but still new. I'll check what's going on, in case the fix is simple.

**Comment by mrc0mmand** [comment]
I'll waive the CI, since resolving this would require a bit of fiddling around.

**Comment by mrc0mmand** [comment]
> I'll waive the CI, since resolving this would require a bit of fiddling around.

Just FTR, I filed the issue as https://github.com/redhat-plumbers/systemd-rhel8/issues/434, since we'll most likely hit it again with later PRs.

**Pull request merged**
