### PR TITLE
(RHEL-65343) backport https://github.com/systemd/systemd/issues/15654#issuecomment-623396457 to RHEL 8.6

### PR DESCRIPTION
**Pull request by tcornell-bus**
I have cherry-picked seven existing commits from the rhel-8.10 branch:
a0b52398692f3e4bda18520db9e2397f7b2c80dd
d8fabe7a6839eeb0d5d0504471f2d18b07545238  
cd85a657c932725ac7c1b506dc6dd4270d1dc068  
538bd9b42dabf1145cf7ab77f32347d516b01e88  
e019afeefb396ea42d03f4c3f9713e262aff6450  
afcfb65ce7514bf32e59e0b9d212ae18d023a4b5  
2f55aeadef3dcdf65c61f24a41178148c3544ac3

Replicating this [pull request](https://github.com/redhat-plumbers/systemd-rhel8/pull/273)

Resolves: RHEL-65343

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Hey, could you also cherrypick following commits from the main branch to make CIs happy?

- 3aae10768d08007dc087306431da60f85087ae57
- ca86de228e19cea268ec3eeabc9097d7c28fbf24

There might be more, but let's see if this is enough to make CIs happy for now.

**Review by jamacku — COMMENTED** [review]
@tcornell-bus Please drop reference to old JIRA and Bugzilla in c1eab42 and 
b4cc106 and reference the RHEL-65343

Please also add `rhel-only: ci` to the c1eab42  commit message.

**Comment by mrc0mmand** [comment]
For the CIs https://github.com/redhat-plumbers/systemd-rhel8/commit/a4e0b7ab90c8bc6ecb7bd883f19e5a5834ae9058 should get cherry-picked as well, to make (at least) GH actions happy.

Also, please use `git cherry-pick -x` when cherry-picking commits, it adds a reference to the original commit in a _standardized_ format, so it then parse-able by our automation.

**Comment by tcornell-bus** [comment]
Will do @mrc0mmand! Should I change "[tcornell: This has been cherry picked from downstream systemd-rhel8
commit _hash_]" to the standard "(cherry picked from commit _hash_)" for all the earlier commits as well?

**Comment by mrc0mmand** [comment]
> Will do @mrc0mmand! Should I change "[tcornell: This has been cherry picked from downstream systemd-rhel8 commit _hash_]" to the standard "(cherry picked from commit _hash_)" for all the earlier commits as well?

Yes, please, it'll make them consistent with the rest of the backports.

**Comment by mrc0mmand** [comment]
I don't think the CentOS CI fail is related to this PR (due to C8S EOL we run the tests on C9S, so we're probably missing some patch(es)). I'll check this manually on RHEL 8 and waive the CI afterwards if everything works fine.

**Comment by mrc0mmand** [comment]
Yup, the tests pass locally on RHEL 8, so this is an unrelated issue.

**Review by dtardon — APPROVED** [review]
LGTM

**Pull request merged**
