### PR TITLE
(#2029426) Rework PID change handling in journald

### PR DESCRIPTION
**Pull request by dtardon**

### CODE REVIEW

**Review by msekletar — DISMISSED** [review]
LGTM

**Review by mrc0mmand — DISMISSED** [review]
The test won't work without https://github.com/systemd/systemd/pull/15648, since currently we ignore `--output-fields=` option in the `cat` output mode (`-o cat`):

Fedora:
```
$ journalctl -b -o cat --output-fields=_TRANSPORT -n5
stdout
stdout
stdout
stdout
journal
```

RHEL 8:
```
# journalctl -b -o cat --output-fields=_TRANSPORT -n5
kdump: Starting kdump: [OK]
Started Crash recovery kernel arming.
Startup finished in 701ms (kernel) + 1.617s (initrd) + 36.679s (userspace) = 38.998s.
systemd-hostnamed.service: Succeeded.
Source 104.131.155.175 replaced with 2601:603:b7f:fec0:0:ba11:ba11:ba11 (2.rhel.pool.ntp.org)
```

**Comment by jamacku** [comment]
@dtardon Could you please have a look, thank you.

**Comment by jamacku** [comment]
@dtardon Could you please rebase on the latest `master`. Thank you

**Review by msekletar — APPROVED** [review]
LGTM

**Pull request merged**
