### PR TITLE
(#2024903) systemd memory corruption fixes

### PR DESCRIPTION
**Pull request by jamacku**

### CODE REVIEW

**Review by dtardon — DISMISSED** [review]
LGTM

**Comment by jamacku** [comment]
@mrc0mmand Could you please have a look at CI

**Comment by mrc0mmand** [comment]
> @mrc0mmand Could you please have a look at CI

Backporting https://github.com/redhat-plumbers/systemd-rhel8/commit/ffd20a699280a4732d0fe4cddafe12ee8010ddb6 and https://github.com/redhat-plumbers/systemd-rhel8/commit/8c15742d1194e0db9a2555553e4d77ebb441b3dc should help.

**Comment by mrc0mmand** [comment]
Keeping track of all the necessary backports for each branch is getting harder and harder... the current CentOS CI fail should be fixed once https://github.com/redhat-plumbers/systemd-rhel8/commit/0357dced252b4bbd1b6dede64a8e0a6674eced6f is backported.

**Review by dtardon — APPROVED** [review]
LGTM

**Pull request merged**
