### PR TITLE
(#1764560) Backport journald fuzzers

### PR DESCRIPTION
**Pull request by mrc0mmand**
Originally I wanted to backport only `fuzz-journald-native-fd`, which provides test coverage for BZ#1764560, but we will definitely benefit from the other `journald` fuzzers as well.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Also backported systemd/systemd@937b1171378bc1000a34fcdfe9534d898227e35f to fix the following heap-buffer-overflow:

```
=================================================================
==3742==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c000000231 at pc 0x7f1bc756a8e0 bp 0x7ffe79d0b340 sp 0x7ffe79d0b330
READ of size 1 at 0x60c000000231 thread T0
    #0 0x7f1bc756a8df in cunescape_length_with_prefix ../../../../src/basic/escape.c:319
    #1 0x56373ab4a161 in dev_kmsg_record ../../../../src/journal/journald-kmsg.c:295
    #2 0x56373ab46d3d in LLVMFuzzerTestOneInput ../../../../src/fuzz/fuzz-journald-kmsg.c:14
    #3 0x56373ab47796 in main ../../../../src/fuzz/fuzz-main.c:34
    #4 0x7f1bc6d3b812 in __libc_start_main (/lib64/libc.so.6+0x23812)
    #5 0x56373ab46b6d in _start (/build/build/test/fuzz/sanitize-address-fuzzers/fuzz-journald-kmsg+0x17b6d)
0x60c000000231 is located 0 bytes to the right of 113-byte region [0x60c0000001c0,0x60c000000231)
allocated by thread T0 here:
    #0 0x7f1bc7d28768 in __interceptor_malloc (/lib64/libasan.so.5+0xef768)
    #1 0x7f1bc75205ee in memdup_suffix0 ../../../../src/basic/alloc-util.c:30
    #2 0x56373ab4715f in dummy_server_init ../../../../src/fuzz/fuzz-journald.c:23
    #3 0x56373ab46cf3 in LLVMFuzzerTestOneInput ../../../../src/fuzz/fuzz-journald-kmsg.c:13
    #4 0x56373ab47796 in main ../../../../src/fuzz/fuzz-main.c:34
    #5 0x7f1bc6d3b812 in __libc_start_main (/lib64/libc.so.6+0x23812)
SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../src/basic/escape.c:319 in cunescape_length_with_prefix
Shadow bytes around the buggy address:
  0x0c187fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c187fff8000: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c187fff8010: fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa
  0x0c187fff8020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 fa
  0x0c187fff8030: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
=>0x0c187fff8040: 00 00 00 00 00 00[01]fa fa fa fa fa fa fa fa fa
  0x0c187fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c187fff8060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c187fff8070: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c187fff8080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c187fff8090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3742==ABORTING
```

**Review by jsynacek — APPROVED** [review]
LGTM.

**Comment by jsynacek** [comment]
By the way, the Resolves: line is missing.

**Comment by jsynacek** [comment]
> By the way, the Resolves: line is missing.

Never mind, they are there in the respective commit messages.

**Pull request merged**
